import puppeteer from "puppeteer";
import cloudinary from "cloudinary";
import path from "path";
import fs from "fs";

cloudinary.v2.config({
  cloud_name: process.env.CLOUDINARY_CLOUD_NAME,
  api_key: process.env.CLOUDINARY_API_KEY,
  api_secret: process.env.CLOUDINARY_API_SECRET,
});

/**
 * Generates a two‑column HTML layout and converts it to PDF, then uploads to Cloudinary.
 * @param {object} report – populated Report document (must include interview, candidate, questions)
 * @returns {Promise<string>} – public URL of the uploaded PDF
 */
export async function generateAndUploadPdf(report) {
  const html = `<!DOCTYPE html>
  <html lang="en"><head>
    <meta charset="UTF-8"/>
    <style>
      body {font-family: 'Inter', sans-serif; margin: 40px;}
      .header {text-align: center; margin-bottom: 30px;}
      .grid {display: grid; grid-template-columns: 1fr 1fr; gap: 20px;}
      .question {font-weight: 600;}
      .answer {margin-top: 5px;}
      .rating {color: #4caf50; font-weight: 600;}
      .footer {font-size: 0.8em; margin-top: 40px; text-align: center; color: #666;}
    </style>
  </head><body>
    <div class="header">
      <h1>Interview Report</h1>
      <p><strong>Candidate:</strong> ${report.candidate.name}</p>
      <p><strong>Job Title:</strong> ${report.interview.jobTitle}</p>
      <p><strong>Date:</strong> ${new Date(report.createdAt).toLocaleDateString()}</p>
      <p><strong>Overall Score:</strong> ${report.overallScore}% – ${report.recommendation}</p>
    </div>
    <div class="grid">
      ${report.questions
        .map(
          (q, i) => `
          <div class="question">Q${i + 1}: ${q.question}</div>
          <div class="answer">
            <p><strong>Candidate Answer:</strong> ${q.candidateAnswer}</p>
            <p class="rating">Rating: ${q.rating || q.score || 0}%</p>
            <p><strong>AI Suggestion:</strong> ${q.suggestion}</p>
          </div>`
        )
        .join("\n")}
    </div>
    <div class="footer">Generated by VIRQA – ${new Date().toISOString()}</div>
  </body></html>`;

  const tmpPath = path.join(process.cwd(), "tmp", `report-${report._id}.html`);
  await fs.promises.mkdir(path.dirname(tmpPath), { recursive: true });
  await fs.promises.writeFile(tmpPath, html, "utf8");

  const browser = await puppeteer.launch({ headless: true });
  const page = await browser.newPage();
  await page.goto(`file://${tmpPath}`, { waitUntil: "networkidle0" });
  const pdfBuffer = await page.pdf({ format: "A4", printBackground: true });
  await browser.close();

  const { Readable } = require("stream");
  const stream = Readable.from(pdfBuffer);

  return new Promise((resolve, reject) => {
    const upload = cloudinary.v2.uploader.upload_stream(
      { resource_type: "raw", folder: "interview_reports" },
      (error, result) => {
        if (error) return reject(error);
        resolve(result.secure_url);
      }
    );
    stream.pipe(upload);
  });
}
